version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}gamawabsapi
    build:
      context: .
      dockerfile: src/services/Gamawabs247API/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
    restart: always
    depends_on:
      - gamawabsdb
      - gamawabsredis
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https/
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__ConnectionString=Server=gamawabsdb:5432;Database=gamawabsdb;User Id=admin;Password=Password@123
  
  billprocessorapi:
    image: ${DOCKER_REGISTRY-}billprocessorapi
    build:
      context: .
      dockerfile: src/services/BillProcessorAPI/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
      - ConnectionStrings__ConnectionString=Server=gamawabsdb:5432;Database=billprocessordb;User Id=admin;Password=Password@123
    ports:
      - "8020:80"
      - "8021:443"
    depends_on:
      - gamawabsdb
      - gamawabsredis
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https/

  responseprocessingjob:
    image: ${DOCKER_REGISTRY-}responseprocessingjob
    build:
      context: .
      dockerfile: src/Jobs/Gamasoft.Worker/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ConnectionString=Server=gamawabsdb:5432;Database=gamawabsdb;User Id=admin;Password=Password@123
    ports:
      - "8030:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  formprocessingjob:
    image: ${DOCKER_REGISTRY-}formprocessingjob
    build:
      context: .
      dockerfile: src/Jobs/FormProcessingWorker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ConnectionString=Server=gamawabsdb:5432;Database=gamawabsdb;User Id=admin;Password=Password@123
    ports:
      - "8040:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  broadcastmessageserviceworker:
    image: ${DOCKER_REGISTRY-}broadcastmessageserviceworker
    build:
      context: .
      dockerfile: src/Jobs/BroadcastMessageServiceWorker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ConnectionString=Server=gamawabsdb:5432;Database=gamawabsdb;User Id=admin;Password=Password@123
    ports:
      - "8046:80"
    depends_on:
      - gamawabsdb
      - gamawabsredis

  gamawabsdb:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@123
      - POSTGRES_DB=gamawabsdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432

  gamawabsredis:
    restart: unless-stopped
    command: redis-server /../../usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/../../usr/local/etc/redis/redis.conf
      - redis_data:/data
    ports:
      - "6370:6379"



