version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}gamawabsapi
    build:
      context: .
      dockerfile: src/services/Gamawabs247API/Dockerfile

  responseprocessingjob:
    image: ${DOCKER_REGISTRY}responseprocessingjob

  formprocessingjob:
    image: ${DOCKER_REGISTRY}formprocessingjob

  billprocessorapi:
    image: ${DOCKER_REGISTRY-}billprocessorapi
    build:
      context: .
      dockerfile: src/services/BillProcessorAPI/Dockerfile
  
  gamawabsdb:
    image: postgres:15.1-alpine

  gamawabsredis:
    image: redis:6.2-alpine

  formprocessingworker:
    image: ${DOCKER_REGISTRY-}formprocessingworker
    build:
      context: .
      dockerfile: src/Jobs/FormProcessingWorker/Dockerfile

  gamasoft.worker:
    image: ${DOCKER_REGISTRY-}gamasoft
    build:
      context: .
      dockerfile: src/Jobs/Gamasoft.Worker/Dockerfile

volumes:
  gamawabs_data:
  postgresql_data:



