version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}gamawabsapi
    build:
      context: .
      dockerfile: src/services/Gamawabs247API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      # - ASPNETCORE_HTTPS_PORT=8001
      # - ASPNETCORE_Kestrel__Certificates__Default__Password=GAMAWABS123456789@*@gama
      # - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx

    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - gamawabsdb
      - gamawabsredis
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https/
      # - ~/root/.aspnet/DataProtection-Keys:ro
  
  billprocessorapi:
    image: ${DOCKER_REGISTRY-}billprocessorapi
    build:
      context: .
      dockerfile: src/services/BillProcessorAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=8021
      - ASPNETCORE_Kestrel__Certificates__Default__Password=GAMAWABS123456789@*@gama
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8020:80"
      - "8021:443"
    depends_on:
      - gamawabsdb
      - gamawabsredis
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/https/
      # - ~/root/.aspnet/DataProtection-Keys:ro

  responseprocessingjob:
    image: ${DOCKER_REGISTRY-}responseprocessingjob
    build:
      context: .
      dockerfile: src/Jobs/Gamasoft.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8030:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  formprocessingjob:
    image: ${DOCKER_REGISTRY-}formprocessingjob
    build:
      context: .
      dockerfile: src/Jobs/FormProcessingWorker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8040:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

  gamawabsdb:
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Password@123
      - POSTGRES_DB=gamawabsdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432

  gamawabsredis:
    restart: unless-stopped
    command: redis-server /../../usr/local/etc/redis/redis.conf
    volumes:
      - ./docker/redis/redis.conf:/../../usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

