version: '3.4'

services:
  responseprocessingjob:
    image: ${DOCKER_REGISTRY-}responseprocessingjob
    build:
      context: .
      dockerfile: src/Jobs/Gamasoft.Worker/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8030:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      # - ~/root/.aspnet/DataProtection-Keys:ro
