version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/services/API/Dockerfile

  businessconfigworker:
    image: ${DOCKER_REGISTRY-}businessconfigworker
    build:
      context: .
      dockerfile: src/Jobs/BusinessConfigWorker/Dockerfile


  formprocessingworker:
    image: ${DOCKER_REGISTRY-}formprocessingworker
    build:
      context: .
      dockerfile: src/Jobs/FormProcessingWorker/Dockerfile


  gamasoft.worker:
    image: ${DOCKER_REGISTRY-}gamasoft
    build:
      context: .
      dockerfile: src/Jobs/Gamasoft.Worker/Dockerfile


  gamasoft.360webhookconfig:
    image: ${DOCKER_REGISTRY-}gamasoft
    build:
      context: .
      dockerfile: src/Jobs/Gamasoft.360WebhookConfig/Dockerfile

