version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}gamawabsapi
    container_name: gamawabs-api
    build:
      context: .
      dockerfile: src/services/API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8000:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      # - ~/root/.aspnet/DataProtection-Keys:ro
