version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}gamawabsapi
    build:
      context: .
      dockerfile: src/services/API/Dockerfile
  
  gamawabsdb:
    image: postgres:15.1-alpine

  gamawabsredis:
    image: redis:6.2-alpine

volumes:
  gamawabs_data:
  postgresql_data:

